{application,cerlicue,
             [{description,[]},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{cerlicue_app,[]}},
              {env,[]},
              {modules,[cerlicue_app,cerlicue_sup,cerlicue_tcp_handler,
                        cerlicue_tcp_handler_sup]}]}.
